### ISSUE TITLE
Failed to draft pattern

### ISSUE THREAD

**Issue by Katesfolly** [freesewing/site#42] opened 2017-07-20 18:33 UTC
This draft went off the rails:
theme=Paperless&lang=en&scope=all&chestEase=12&waistEase=16&hipsEase=12&bicepsEase=3&collarEase=1.5&cuffEase=3.5&lengthBonus=15&sleeveLengthBonus=2&yokeDart=0.4&hipFlare=2&buttonfreeLength=2.5&hemStyle=1&hemCurve=8&buttons=7&extraTopButton=1&splitYoke=1&buttonPlacketType=1&buttonPlacketStyle=1&buttonPlacketWidth=2&buttonholePlacketType=1&buttonholePlacketStyle=2&buttonholePlacketWidth=3&buttonholePlacketFoldWidth=0.64&sleevePlacketWidth=1.8&sleevePlacketLength=14&collarStandWidth=3&collarStandBend=0.5&collarStandCurve=0.5&collarGap=2.5&collarBend=1.5&collarFlare=1&collarAngle=8.5&collarRoll=0.7&cuffStyle=2&cuffLength=6&cuffButtonRows=1&barrelcuffNarrowButton=1&cuffDrape=3&armholeDepthFactor=60&sleevecapHeightFactor=50&sleevecapEase=0.2&pattern=SimonShirt&model=vnktz

This data was returned::
{"readyState":0,"status":0,"statusText":"error"}

Feel free to include comments, but please keep the info above.

**Comment by joostdecock** [comment] 2017-07-21 09:23
I tried recreating this, but I was unable to.
Would you mind giving this another go to see whether the problem is still present?

Thanks

**Comment by Katesfolly** [comment] 2017-07-21 15:00
Sure!
So, when I did the Simon draft with no mods, it drafted fine. When I
triggered the original error, I had messed with the settings, so I
re-checked, and:


   - Changing only general option to paperless caused no issue
   - Changing cuff ease caused no issue
   - Changing button free length and yoke dart caused no issue
   - Changing baseball hem and split yoke caused no issue
   - changing buttonhole and sleeve placket length and width caused no issue
   - Changing collar stand width caused no issue


   - Changing cuff width and cuff drape settings appears to trigger the
   issue!

Maybe try looking at those settings?

I just joined GitHub, so I could submit issues a little more user-friendly
to you, but I'm a total newbie, so if I do anything wrong, please let me
know!

Also, in case it isn't captured in the error sent via the GitHub button, I
have gotten this same error on Safari for Mac and Firefox for Windows.

Thanks!
AJ

**Comment by joostdecock** [comment] 2017-07-22 17:52
You are being so incredibly helpful, I can't thank you enough 👍 

The detailed description is great, I will certainly check out those two options. Probably on Monday because I'm kinda busy this weekend. But I'll get around to it.

**Comment by joostdecock** [comment] 2017-07-23 17:47
I'm posting this here because I don't think I'll have fine to figure out what's going on tonight.
But this is the error it's throwing:

```
PHP Warning:  Division by zero in /home/joost/git/core/src/Utils/Utils.php on line 174
PHP Stack trace:
PHP   1. {main}() /home/joost/git/core/index.php:0
PHP   2. Freesewing\Context->runService() /home/joost/git/core/index.php:23
PHP   3. Freesewing\Services\DraftService->run() /home/joost/git/core/src/Context/Context.php:544
PHP   4. Freesewing\Patterns\Core\SimonShirt->draft() /home/joost/git/core/src/Services/DraftService.php:61
PHP   5. Freesewing\Patterns\Core\SimonShirt->finalizeCollarStand() /home/joost/git/core/patterns/Core/SimonShirt/SimonShirt.php:149
PHP   6. Freesewing\Part->offsetPath() /home/joost/git/core/patterns/Core/SimonShirt/SimonShirt.php:1950
PHP   7. Freesewing\Part->offsetPathSegments() /home/joost/git/core/src/Part/Part.php:622
PHP   8. Freesewing\Part->offsetCurve() /home/joost/git/core/src/Part/Part.php:2533
PHP   9. Freesewing\Part->offsetCurve() /home/joost/git/core/src/Part/Part.php:1308
PHP  10. Freesewing\Part->offsetCurve() /home/joost/git/core/src/Part/Part.php:1308
PHP  11. Freesewing\Part->offsetCurve() /home/joost/git/core/src/Part/Part.php:1308
PHP  12. Freesewing\Part->getCurveOffsetPoints() /home/joost/git/core/src/Part/Part.php:1259
PHP  13. Freesewing\Part->beamsCross() /home/joost/git/core/src/Part/Part.php:1196
PHP  14. Freesewing\Utils::lineLineIntersection() /home/joost/git/core/src/Part/Part.php:1778
```

We have a division by zero in [this method](https://github.com/freesewing/core/blob/develop/src/Utils/Utils.php#L174) that finds the intersection between two lines.

**Comment by joostdecock** [comment] 2017-07-23 18:12
I've pushed [an update](https://github.com/freesewing/core/commit/20e07048ff187431086417fc1824ac647084759d) to core that should fix this. I would appreciate it if you could confirm.

Also, and this has nothing to do with the issue, I think you might want to set the across back measurement to 34.5cm. It currently is 30.5cm and that seems too low in comparison to the chest circumference.
The pattern will adapt as needed, but because of the big difference (relatively big given the small size) the reduction from shoulder to yoke is very big, which is why your yoke and armholes look so weird.

Set the across back to 34.5cm and you'll get a much better draft. 
But before you do so, make sure to test it with the original measurements just to make sure it's fixed.

Also, is this for a child? And if so, are you sure about the length of their arms? They are very long in comparison to the rest.

It's always a bit tricky to suggest some measurements look off. Because maybe those are your measurements and me suggesting otherwise might be hurtful. So please understand that I'm just trying to help.

love
joost

**Comment by Katesfolly** [comment] 2017-07-23 19:37
Joost,

So, unfortunately it looks like reducing with the cuff ease still is
causing the problem for me, but ONLY if the cuff ease is between 2.05 cm
and 3 cm. 3cm throws the error, 3.05 does not. 2.05 throws the error, 2.0
does not. I sent a report through GitHub in case that gives you any
additional info you'll need. I redrafted Simon several times with various
updated model measurements without issue. I probably cluttered up the
database a little with that big bunch of redrafts!

RE: your comments on the actual measurements, there were definitely a
couple of problems--including the back width. I prefer to work with cm for
ease of use, but since my life is Imperial generally (Americans, there's no
help for us), I usually don't notice typos or "weird-looking" numbers when
I work with cm. Whoops! I appreciate you pointing that out.

But also--I do have pretty long arms...try finding a 12.5 neck shirt with
32 inch sleeves sometime, and you'll know why I sew!  I'm looking forward
to drafting Simon for my other model, because I have a good hand-drafted
pattern for him and I'll be able to compare (also from the Winifred
Aldrich, which I believe you said you use as well).

Thanks again!
-AJ

**Comment by joostdecock** [comment] 2017-07-24 07:50
For info: Simon is not based on Aldrich. It's based on Brian (basic body block) which in turn is based on Gareth Kershaw's method with my own modifications for a better shoulder fit.

A few notes mostly for my own reference:

- [This drafts Simon in the measurements you used (no options)](https://dev.core.freesewing.org/?service=draft&pattern=SimonShirt&theme=Basic&acrossBack=30.5&bicepsCircumference=22.3&centerBackNeckToWaist=40.6&chestCircumference=82.5&naturalWaistToHip=9.5&neckCircumference=32.5&shoulderToShoulder=37.5&shoulderSlope=4.5&hipsCircumference=79&naturalWaist=62.5&shoulderToWrist=73.1&wristCircumference=13.75&shoulderToElbow=32.5)

Note that that does not trigger the problem. We'll need to tweak the options for that.

The problem itself seems due to this:

```
PHP Notice:  Undefined index: pleatRightTop in /fs/deploy/core/develop/builds/current/src/Part/Part.php on line 1463
PHP Fatal error:  Uncaught Error: Call to a member function getY() on null in /fs/deploy/core/develop/builds/current/src/Part/Part.php:1463\nStack trace:
#0 /fs/deploy/core/develop/builds/current/patterns/Core/SimonShirt/SimonShirt.php(2492): Freesewing\\Part->y('pleatRightTop')
#1 /fs/deploy/core/develop/builds/current/patterns/Core/SimonShirt/SimonShirt.php(161): Freesewing\\Patterns\\Core\\SimonShirt->paperlessSleeve(Object(Freesewing\\Model))
#2 /fs/deploy/core/develop/builds/current/src/Services/DraftService.php(61): Freesewing\\Patterns\\Core\\SimonShirt->draft(Object(Freesewing\\Model))
#3 /fs/deploy/core/develop/builds/current/src/Context/Context.php(544): Freesewing\\Services\\DraftService->run(Object(Freesewing\\Context))
#4 /fs/deploy/core/develop/builds/current/index.php(23): Freesewing\\Context->runService()
#5 {main}\n  thrown in /fs/deploy/core/develop/builds/current/src/Part/Part.php on line 1463
```

It's an issue caused by the cuff pleats, which is consistent with what you reported. 
Next step is to try and replicate the options that trigger it, then fix it :)

**Comment by joostdecock** [comment] 2017-07-24 08:12
Aha, [this URL](https://dev.core.freesewing.org//index.php?theme=Paperless&lang=en&scope=all&chestEase=12&waistEase=16&hipsEase=12&bicepsEase=3&collarEase=1.5&cuffEase=3&lengthBonus=15&sleeveLengthBonus=3&yokeDart=0.4&hipFlare=2&buttonfreeLength=2&hemStyle=2&hemCurve=8&buttons=7&extraTopButton=1&splitYoke=1&buttonPlacketType=1&buttonPlacketStyle=1&buttonPlacketWidth=2&buttonholePlacketType=1&buttonholePlacketStyle=2&buttonholePlacketWidth=3&buttonholePlacketFoldWidth=0.64&sleevePlacketWidth=2&sleevePlacketLength=15&collarStandWidth=2.75&collarStandBend=0.5&collarStandCurve=0.5&collarGap=2.5&collarBend=1.5&collarFlare=1&collarAngle=8.5&collarRoll=0.7&cuffStyle=2&cuffLength=5.5&cuffButtonRows=1&barrelcuffNarrowButton=1&cuffDrape=2.2&armholeDepthFactor=60&sleevecapHeightFactor=50&sleevecapEase=0.5&pattern=SimonShirt&model=vnktz&draft=sbcyv&seatDepth=27.5&centerBackNeckToWaist=40.6&chestCircumference=82.5&inseam=77.5&naturalWaist=62.5&shoulderToWrist=59&underBust=71.8&wristCircumference=13.75&acrossBack=34.5&bicepsCircumference=22.3&headCircumference=56.3&hipsCircumference=79&hipsToUpperLeg=22.5&naturalWaistToHip=9.5&naturalWaistToUnderbust=17&neckCircumference=32.5&seatCircumference=87.5&shoulderSlope=4.5&shoulderToElbow=30.5&shoulderToShoulder=39&upperLegCircumference=46.6&unitsIn=metric&unitsOut=metric&reference=sbcyv&service=draft) reproduces the problem.

The tricky part it that it only happens in the **Paperless** theme, which is probably why it was so hard to pin down. Now that I know that, it shouldn't be that hard to figure out what's going on.

**Comment by joostdecock** [comment] 2017-07-24 08:31
This was due to the decision whether to add 1 or 2 pleats to the cuff was different in two places.
At one, it was two pleats when cuff drape is more than 3cm. On the other, it was two pleats when cuff drape was more than 2cm.

This meant that when you had a cuff drape between 2cm and 3cm, part of the pattern expected to have 2 pleats, while another part expected 1.
So only one pleat was drawn, but then we expected the second pleat to mark the pleat width with the dimensions in the paperless pattern.

So yeah, a bona fide bug and I'm really glad you reported this.

[This update to core](https://github.com/freesewing/core/commit/f57f807467e5878ab7a993975e43725c7b7be3dc) fixes the issue. The URL I posted above now works (when it would fail before), but I'll let you double-check before closing this issue.

**Comment by Katesfolly** [comment] 2017-07-24 14:53
Tested, I was unable to find any persisting errors, yay!  I also fiddled with the remaining Simon settings I hadn't tried (the Advanced bunch) and found no issues there. 

If you have preference about where/how I work next, just let me know.  I was kind of planning on drafting all the patterns at least once, to paperless, then doing a draft-and-sew for two Aarons, and beyond that I didn't really have a plan. Most of the undies in my house are already made off the old version of Bruce from MMP, so I could redraft that and compare.  :)

Good to know about the block basis for Simon--a well-fitted pattern is a well fitted pattern, so I imagine the two methods will come out quite similar but it will doubtless be fun to compare and contrast.  (Um, if you're a huge nerd, which apparently I am!)

Thanks!

**Comment by joostdecock** [comment] 2017-07-24 15:00
Thanks for confirming that this is resolved :+1: 

Remaking a Bruce would be a good idea because it's completely redesigned form scratch. Apart from that, I'm making cosmetic changes these days (like updating the email templates and documentation) so that's not that prone to blowing up.

Also, freesewing is for nerds. Wasn't that obvious? ;-)

**Closed by joostdecock** 2017-07-24 15:00 UTC
Labels: bug, unconfirmed fix
