### ISSUE TITLE
Problem with draft gwqdt

### ISSUE THREAD

**Issue by SJKurtz** [freesewing/site#39] opened 2017-07-20 01:02 UTC
See [here](dev.freesewing.org/drafts/gwqdt)
Ah, Simon's collar is crazy, but it looks more normal. 
I did realize I had a measurement error on my model (shoulder) and amended it. I am not seeing a place to change from imperial to metric, but I need dinner and will double check my account and options.

Stephanie M

**Comment by joostdecock** [comment] 2017-07-20 06:52
I'm working on all things imperial at the moment. See issue #31 that's open for it. 

There's certainly something wrong with the pattern, but it's because the input it wrong.
There's things that don't make sense. Like the collar stand height is 3.5 inch, which is Karl Lagerfeld style crazy. Whereas 3.5cm is perfectly normal, so there might have been a mixup there.

The draft is rendered in imperial, is that what you intended?

Also, some of the measurements are probably wrong. Your shoulder-to-shoulder is less than your across-back. That's not possible.

I'll be making more changes to the imperial stuff later today. Perhaps it best to see whether we can reproduce these issues afterwards.

In any case, thanks for your feedback.

**Comment by joostdecock** [comment] 2017-07-20 09:39
I've rolled out a bunch of updates for imperial (see https://github.com/freesewing/site/issues/31 )

As such, this is outdated and I'm going to close this. Please try to reproduce this and open a new issue if you can.

**Closed by joostdecock** 2017-07-20 09:39 UTC
