### ISSUE TITLE
Redraft does nothing

### ISSUE THREAD

**Issue by PD75** [freesewing/site#118] opened 2017-10-07 11:10 UTC
Redrafting changes nothing, even if I change settings.. I have the same problem with both wahid and theo, so now I create a new draft when I need to redraft and delete the old.

**Comment by joostdecock** [comment] 2017-10-07 12:51
Could it be that your browser is simple showing you the cached preview?

Please redraft a draft with changed settings, then either open the draft in a new window and hit Ctrl-D, or download the full-size PDF to compare.

Thanks for testing this and getting back to me

**Comment by joostdecock** [comment] 2017-10-07 13:15
I meant Ctrl-reload (to refresh the cache)

**Comment by PD75** [comment] 2017-10-07 18:15
I tried nothing, happened, but when I redrafted now it showed paperless view, which I selected a few draft ago, and could get on full size-PDF (downloading it) but did not show on the page. However I am unable to switch from "Only selected parts" to "Complete pattern" it keeps the old settings.

**Comment by joostdecock** [comment] 2017-10-07 18:18
Can you give me the draft reference,or a link to it? I'll have a look

**Comment by PD75** [comment] 2017-10-07 18:57
https://freesewing.org/drafts/urbnf

Sorry forgot to paste.

**Comment by joostdecock** [comment] 2017-10-09 09:08
There is no draft **urbnf** :(

**Comment by PD75** [comment] 2017-10-10 05:24
Sorry, I left drafting stage, and started execute, I was a bit over zealous cleaning up.

Here is a new https://freesewing.org/drafts/sptqm

I did find a workaround eventually, not select complete pattern , but rather all other pieces. Works after a few times, but does not update the picture on the page.

**Comment by joostdecock** [comment] 2017-10-13 09:17
Sorry for the delay, I've been ill lately.

There's two issues we're dealing with here:

**The picture is not updated when changes to the options are made**

I cannot reproduce this, and I am rather confident it's a browser caching issue. 
I could look into options to bust the cache by passing some random parameters, but I'll have to think about it.

**Selecting parts in the scope, and then whole pattern again, does not not give the expected result**

I can **can** reproduce this and it's a bug. I'm going to see how I can fix it and I'll report here.

The reason this happens is because the code checks whether you have selected individual parts in the scope. If you have, it gives you those parts.

But if you have selected parts, and then redraft and pick *Full pattern* those selected parts are not un-selected. They are still there, just hidden. And the code then doesn't realize you want something different.

A workaround is selecting everything (as you did) or selecting nothing, which will also fix it.

Eitherway, I'll try to fix this ASAP, thanks for reporting it. If you can let me know your username on the site, I will assign the bug badge to your profile, you've earned it :)

**Comment by PD75** [comment] 2017-10-13 09:22
It is that time of year...hope you are feeling better!

We had similar problems with the picture and caching issue previously with an in-house application, our programmer solved it by giving all images a GUID which was regenerated every time the image changed. That way the browser loaded a "new picture". Another option is to set a very low cache expiry, but that makes the page slower to load.

**Comment by PD75** [comment] 2017-10-13 09:23
My user is Tiger751023.

**Comment by joostdecock** [comment] 2017-10-13 09:34
Does that mean I can wish you a belated happy birthday? :)

**Comment by PD75** [comment] 2017-10-13 09:40
10 days to go...Sweden uses yymmdd... will (hopefully) wear Wahid + Theodore for the day :-)

**Comment by joostdecock** [comment] 2017-10-13 09:41
Oh yeah, obviously. I got the month wrong somehow. Send pictures! :)

**Comment by PD75** [comment] 2017-10-13 09:45
I will! Actually Wahid ready, wearing it right now, Theodore in bits and pieces at home.

**Comment by joostdecock** [comment] 2017-10-13 10:00
Great, looking forward to it!

Also, I've given you the bug and issue badges in your profile, and I've fixed both of the problems outlined above:

**The picture is not updated when changes to the options are made**

When loading draft data from the backend, it now includes a **cache** value that is the SHA1 hash of all the pattern options (if any of the options change, the hash changes).

In the frontend, this hash is passed as a cache parameter. If it changes, the URL changes, overriding browser/proxy cache.

This should fix the caching issue.

**Selecting parts in the scope, and then whole pattern again, does not not give the expected result**

That is fixed by not passing the part list to the backend when the scope is set to **all**.

Thanks again for reporting this, I'm closing this now.

**Closed by joostdecock** 2017-10-13 10:00 UTC
