### ISSUE TITLE
Issue when mixing imperial and metric units

### ISSUE THREAD

**Issue by lmay0013** [freesewing/site#158] opened 2017-11-01 20:12 UTC
See [here](https://freesewing.org/drafts/gnpca)

On the Front Left pattern piece, the seam allowance at the top of the shoulder doesn't follow the standard 1cm and instead angles in to the shirt. I'm thinking I just need to add it back on, but is there something I am missing?

Thanks!

**Comment by joostdecock** [comment] 2017-11-02 08:57
Hmm, that's not supposed to happen. Thanks for reporting it, I've assigned you [the issue badge](https://freesewing.org/users/wvcqr) for it.

This is caused by the path offset code getting confused. Offsetting bezier curves is surprisingly complex, and this is a case where it goes off the rails.

I will have a look at it and see if I can get it to behave. Meanwhile, as you already figured out, you can simply add the SA to the shoulderseam.

**Comment by lmay0013** [comment] 2017-11-02 12:22
Thanks! I’ve added it back in.

**Comment by joostdecock** [comment] 2017-11-02 18:00
This issue has me concerned. Here's the thing:

- Your units are metric (in your profile)
- Your model's units are imperial (in the model settings)

This is somewhat uncommon. Is this on purpose, or are you unaware that your profile is set to metric?

Now here's the thing that has me concerned: [This](https://core.freesewing.org/index.php?seamAllowance=metric&customSa=1&scope=all&theme=Basic&lang=en&chestEase=16&waistEase=16&hipsEase=16&bicepsEase=4&collarEase=1.5&cuffEase=3.5&lengthBonus=12.5&sleeveLengthBonus=2.55&yokeDart=0.5&hipFlare=1&buttonfreeLength=1&hemStyle=2&hemCurve=7&buttons=7&extraTopButton=1&splitYoke=1&buttonPlacketType=1&buttonPlacketStyle=2&buttonPlacketWidth=2&buttonholePlacketType=1&buttonholePlacketStyle=2&buttonholePlacketWidth=3.5&buttonholePlacketFoldWidth=0.64&sleevePlacketWidth=2.5&sleevePlacketLength=18&collarStandWidth=3.5&collarStandBend=0.5&collarStandCurve=0.5&collarGap=2.5&collarBend=1.5&collarFlare=1&collarAngle=85&collarRoll=0.7&cuffStyle=2&cuffLength=6.5&cuffButtonRows=1&barrelcuffNarrowButton=1&cuffDrape=4&armholeDepthFactor=60&sleevecapHeightFactor=50&sleevecapEase=0.5&sa=1&userUnits=metric&fork=true&pattern=SimonShirt&model=mhyev&draft=gnpca&chestCircumference=40&naturalWaist=34.5&shoulderToWrist=24&hipsCircumference=35&inseam=30&acrossBack=17&bicepsCircumference=13.75&centerBackNeckToWaist=15&naturalWaistToHip=4&neckCircumference=15.75&shoulderToShoulder=18&shoulderSlope=2&wristCircumference=6.75&shoulderToElbow=13&unitsIn=imperial&unitsOut=imperial&reference=gnpca&service=draft) is the API call that was used to generate your pattern. It's super long, but I've narrowed it down to this to replicate the issue:

[https://core.freesewing.org/index.php?service=draft&pattern=SimonShirt&sa=1&buttonholePlacketWidth=3.5&sa=1&unitsIn=imperial&theme=Designer](https://core.freesewing.org/index.php?service=draft&pattern=SimonShirt&sa=1&buttonholePlacketWidth=3.5&sa=1&unitsIn=imperial&theme=Designer)

The important thing here is the `unitsIn` parameter that is set to `imperial`. But because your profile is set to `metric`, the options are actually in metric. 

For example, the `buttonholePlacketWidth` option is set to 3.5. This is the default 3.5 cm that is interpreted as 3.5" here. 3.5" is 8.9cm, but since the option has an upper boundary of 4.5cm you end up with 4.5cm.

Not only is that probably not what you wanted, it also illustrate that things aren't working as expected when you mix different units between model and your own user settings.

Note that none of this does technically explain the issue with the seam allowance. But you are hitting some corner case that people typically don't get into because of the difference between your user units and model units.

Could you do me a favor: Would you change your settings to imperial, and see whether that makes a difference?

thanks in advance,
joost

**Comment by joostdecock** [comment] 2017-11-02 18:03
Actually, there's another thing I'd like you to try first. Simply **redraft** this draft.

I'd like to see whether that makes a difference because the backend does things slightly different for a redraft.

**Comment by lmay0013** [comment] 2017-11-02 18:29
I started with the redraft, but that didn't make a difference. The shoulder
seam was still off.

After that, I switched my profile to imperial to match he model
measurements and then redrafted. It looks good now.

I didn't realize there was a setting in the profile for measurements or I
would have switched it earlier. As I was going through the draft of the
pattern I kept converting everything to imperial so it would make more
sense to me. :)

I'm excited to put this pattern together. My husband usually buys custom
made shirts as ready to wear never fit him very well. Thanks for your help
and taking the time to make such an amazing tool!

Regards,
Leah

**Comment by joostdecock** [comment] 2017-11-03 05:43
Glad to hear it's sorted for you. I'm going to keep this issue open as a reminder to myself that this might need some attention for other people who are in a similar situation.

Good luck with the shirts, don't forget to send in some pictures ;)

**Comment by joostdecock** [comment] 2017-11-07 10:33
The issue with the mixed metric/imperial units is fixed. Turns out it was only present when redrafting a pattern, which is why it escaped my attention at first.

Here's the fix: https://github.com/freesewing/data/commit/92c1ebca13eed386105d4ff46ad9ad356f257144

It's deployed in production, I'm closing this :)

**Closed by joostdecock** 2017-11-07 10:33 UTC
