### ISSUE TITLE
Failed to draft pattern (Simon, follow-up to previous issue)

### ISSUE THREAD

**Issue by Katesfolly** [freesewing/site#45] opened 2017-07-23 19:06 UTC
Triggered by adjusting the cuff drape down to 3 cm.

This draft went off the rails:
theme=Paperless&lang=en&scope=all&chestEase=12&waistEase=16&hipsEase=12&bicepsEase=3&collarEase=1.5&cuffEase=3&lengthBonus=15&sleeveLengthBonus=3&yokeDart=0.4&hipFlare=2&buttonfreeLength=2&hemStyle=2&hemCurve=8&buttons=7&extraTopButton=1&splitYoke=1&buttonPlacketType=1&buttonPlacketStyle=1&buttonPlacketWidth=2&buttonholePlacketType=1&buttonholePlacketStyle=2&buttonholePlacketWidth=3&buttonholePlacketFoldWidth=0.64&sleevePlacketWidth=2&sleevePlacketLength=15&collarStandWidth=2.75&collarStandBend=0.5&collarStandCurve=0.5&collarGap=2.5&collarBend=1.5&collarFlare=1&collarAngle=8.5&collarRoll=0.7&cuffStyle=2&cuffLength=5.5&cuffButtonRows=1&barrelcuffNarrowButton=1&cuffDrape=3&armholeDepthFactor=60&sleevecapHeightFactor=50&sleevecapEase=0.5&pattern=SimonShirt&model=vnktz&draft=sbcyv

This data was returned::
{"readyState":0,"status":0,"statusText":"error"}

Feel free to include comments, but please keep the info above.

**Comment by joostdecock** [comment] 2017-07-24 07:34
Thanks for reporting this again. I will mark this a duplicate to keep all info tied to one issue.

Duplicate of #42

**Closed** 2017-07-24 15:00 UTC
Labels: bug, duplicate, unconfirmed fix
